CXXFLAGS+=-std=c++17
CXXFLAGS+=-pthread

#LDFLAGS+=-lboost_atomic
#LDFLAGS+=-lboost_chrono
#LDFLAGS+=-lboost_container
#LDFLAGS+=-lboost_context
#LDFLAGS+=-lboost_contract
#LDFLAGS+=-lboost_coroutine
#LDFLAGS+=-lboost_date_time
#LDFLAGS+=-lboost_filesystem
#LDFLAGS+=-lboost_graph
#LDFLAGS+=-lboost_iostreams
#LDFLAGS+=-lboost_locale
#LDFLAGS+=-lboost_log_setup
#LDFLAGS+=-lboost_log
#LDFLAGS+=-lboost_math_c99f
#LDFLAGS+=-lboost_math_c99l
#LDFLAGS+=-lboost_math_c99
#LDFLAGS+=-lboost_math_tr1f
#LDFLAGS+=-lboost_math_tr1l
#LDFLAGS+=-lboost_math_tr1
#LDFLAGS+=-lboost_prg_exec_monitor
#LDFLAGS+=-lboost_program_options
#LDFLAGS+=-lboost_random
#LDFLAGS+=-lboost_regex
#LDFLAGS+=-lboost_serialization
#LDFLAGS+=-lboost_stacktrace_addr2line
#LDFLAGS+=-lboost_stacktrace_backtrace
#LDFLAGS+=-lboost_stacktrace_basic
#LDFLAGS+=-lboost_stacktrace_noop
#LDFLAGS+=-lboost_system
#LDFLAGS+=-lboost_thread
#LDFLAGS+=-lboost_timer
#LDFLAGS+=-lboost_type_erasure
#LDFLAGS+=-lboost_unit_test_framework
#LDFLAGS+=-lboost_wave
#LDFLAGS+=-lboost_wserialization

all: boost-cheat
